# Generated by Django 3.1.1 on 2021-04-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_remove_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Like Count'),
        ),
    ]
