# Generated by Django 3.1.1 on 2021-04-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='tweet',
        ),
    ]
